"""add_status_to_ai_models

Revision ID: f7d735a7befd
Revises: 0472b5a82e80
Create Date: 2026-03-17 11:46:12.066353

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7d735a7befd"
down_revision: Union[str, Sequence[str], None] = "0472b5a82e80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_models", sa.Column("status", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_models", "status")
    # ### end Alembic commands ###
